add solutions
js-tasks-ru/htmlcss-20211125_viki pull request #3
Opened 2022-01-10 18:58 UTC by kramarova

2022-01-10 18:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-13 15:49 UTC, GSemikozov requested changes

2022-01-13 15:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +html {
общие стили определяем в main.css, сбросы - в normalize.css, а если же это стили которые нужны только на странице решения задачи и нигде не будут переиспользоваться - тогда их можно определять на хтмл странице в теге style

2022-01-13 15:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-style: normal;
не хватает font-family

2022-01-13 15:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons__primary {
модификаторы пишем через 1 нижнее подчеркивание (через 2 - элементы)

2022-01-13 15:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons__primary {
и название модификатора начинается с названия блока / элемента к которому он принадлежит, в данном случае должно быть .button_primary

2022-01-13 15:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons__primary {
я понимаю что модификация кнопок происходит по задумке через класс-микс и родительский блок .buttons, но в нашем случае этот вариант можно использовать только для задания например отступов между кнопок (определяем внешнее поведение кнопки внутри блока .buttons). 
Но вообще - здесь нет необходимости заворачивать кнопки в buttons, поэтому советую избавиться от этого класса, а его элементы переделать на модификаторы кнопки

2022-01-13 15:49 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +:root {
как и выше - глобальные штуки нужно определять в соответствующих файлах, но никак не в файле компонента)

2022-01-13 15:49 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  font-size: 2rem;
не хватает font-family)

2022-01-17 19:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-18 19:52 UTC, GSemikozov approved these changes

2022-01-18 19:52 UTC, merged