add new file
js-tasks-ru/htmlcss-20211125_viki pull request #5
Opened 2022-01-19 18:57 UTC by kramarova

2022-01-19 18:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-20 12:46 UTC, GSemikozov requested changes

2022-01-20 12:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
эти стили можно перенести в .modal__content и удалить лишний враппер

2022-01-20 12:46 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 30px;
по дизайну точно так?)

2022-01-21 08:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-21 19:54 UTC, GSemikozov approved these changes

2022-01-21 19:54 UTC, merged